# Generated by Django 2.0.3 on 2019-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=64)),
                ('Name', models.CharField(max_length=64)),
                ('Size', models.CharField(max_length=64)),
                ('Cost', models.FloatField()),
                ('No_of_toppings', models.IntegerField()),
            ],
        ),
    ]
