# Generated by Django 2.0.3 on 2019-07-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Size',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
