# Generated by Django 2.0.3 on 2019-07-08 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_addition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='addition',
            old_name='Cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='addition',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='No_of_toppings',
            new_name='no_of_toppings',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='Name',
            new_name='name',
        ),
    ]
