# Generated by Django 2.0.3 on 2019-07-08 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_auto_20190708_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('addition', models.ManyToManyField(blank=True, related_name='cart_additions', to='orders.Addition')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('Subs', 'Subs'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Dinner Platter', 'Dinner Platter')], max_length=64),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='orders.Menu'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='cart_toppings', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
