# Generated by Django 2.0.3 on 2019-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190708_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='topping',
            field=models.ManyToManyField(related_name='cart_toppings', to='orders.Topping'),
        ),
    ]
